name: Build and Deploy ASP.NET Core App

on:
  [workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: List files in the API directory
        run: ls -la

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sardorbek96
          password: dckr_pat_UUz7DZY7fTm8maEXG0dYUnI5RHw
    
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          tags: sardorbek96/simple_project_azure:dev-latest
          push: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
      - name: Log In to Azure Container App
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'sardorbek'
          images: 'sardorbek96/simple_project_azure:dev-latest'
      
