name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sardorbek96
          password: dckr_pat_UUz7DZY7fTm8maEXG0dYUnI5RHw

      - name: Build Docker image
        run: docker build -t sardorbek96/simple_project_azure:v1.0.0 .

      - name: Push Docker image to Docker Hub
        run: docker push  sardorbek96/simple_project_azure:v1.0.0

  deploy:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sardorbek96
          password: dckr_pat_UUz7DZY7fTm8maEXG0dYUnI5RHw

      - name: Log in to Azure Container App
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: 'sardorbek'
          publish-profile:  ${{ secrets.AZURE_CREDENTIALS_P }}
          images: ardorbek96/simple_project_azure:v1.0.0
          
