name:  Build and Deploy Simple App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t sardorbek96/simple_project_azure:${{ github.run_id }} .

      - name: Push Docker image to Docker Hub
        run: docker push  sardorbek96/simple_project_azure:${{ github.run_id }}
  
  dev:
    runs-on: ubuntu-latest

    needs: build
    environment: development

    env:
      ENVIRONMENT_PREFIX: dev
      TAG_ENVIRONMENT: DEVELOPMENT

    steps:
      - name: Log in to Azure Container App
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: 'sardorbek'
          publish-profile:  ${{ secrets.AZURE_CREDENTIALS_P }}
          images: sardorbek96/simple_project_azure:${{ github.run_id }}
