name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sardorbek96
          password: dckr_pat_UUz7DZY7fTm8maEXG0dYUnI5RHw

      - name: Build Docker image
        run: docker build -t sardorbek96/simple_project_azure:latest .

      - name: Push Docker image to Docker Hub
        run: docker push  sardorbek96/simple_project_azure:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sardorbek96
          password: dckr_pat_UUz7DZY7fTm8maEXG0dYUnI5RHw

      - name: Log in to Azure Container App
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_SP_CREDENTIALS }}


      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'sardor'
          images: ardorbek96/simple_project_azure:latest
