name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sardorbek96
          password: dckr_pat_UUz7DZY7fTm8maEXG0dYUnI5RHw

      - name: Build Docker image
        run: docker build -t sardorbek96/simple_project_azure:latest .

      - name: Push Docker image to Docker Hub
        run: docker push your-dockerhub-username/your-image-name:latest


  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  
  #   steps:
  #     - name: Log In to Azure Container App
  #       uses: azure/login@v1
  #       with:
  #         client-id: af22c1fb-6be2-4fee-8d3c-0b349f13f3cb
  #         tenant-id: b4be46cf-f412-4c71-9405-35113a8dc0f9
  #         subscription-id: c2021b07-37a5-4dd4-b829-955dac223bb9
      
  #     - uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'sardorbek'
  #         images: 'sardorbek96/simple_project_azure:dev-latest'
      
